### PR TITLE
Update for cluster view styles

### PR DESCRIPTION
**Pull request by alexwolfe**
@alex-kovoy I added title tags and updated the styles for the nodes link. See image below: 
image

### CODE REVIEW

**Comment by benarent** [comment]
Thanks for the quick turn around on this @alexwolfe .

My thoughts are.. 
1. How does this look in proxy mode, where we currently report 0 nodes. 
image

2. Similar note, for K8s users, but we might want to roll this into  https://docs.google.com/document/d/1cS6J2d_xBcJMWPewWPjdOZyrDHLKdqmgF1QLLo4E1YI/edit

3. What happens with very high counts, do we show exact counts or count it up / down. e.g. 8, 120, 1k, 3k, 10k nodes?

**Comment by alex-kovoy** [comment]
@benarent , these are good outstanding questions which we can address in 4.4

But do we want to add these sight improvements to the node count hyperlinks in 4.3?

**Comment by benarent** [comment]
I think If we do this; we should at least address the zero issue. If zero; we can just make this look more like a button ( since this design allows it) ; vs giving the illusion of zero nodes but there are many openssh nodes

**Comment by alex-kovoy** [comment]
@benarent @alexwolfe 

> giving the illusion of zero nodes but there are many openssh nodes

How is it different from showing "1 node" where there are still many openssh nodes in the wild? So I guess the confusing part is with the terminal button coupled with the teleport node count.

What if we open the terminal on the cluster name click? And to manage a cluster, a user would use the options dropdown by clicking on "Manage this cluster" option?

**Comment by alex-kovoy** [comment]
has been merged

**Pull request closed without merging**
