### PR TITLE
Add public tunnel address

### PR DESCRIPTION
**Pull request by mcbattirola**
edit: waiting to be merged after https://github.com/gravitational/teleport/pull/10133

## Purpose

Show the reverse tunnel address on `Help & Support` screen.

On cloud instances, we use a custom reverse tunnel port for each tenant. In the UI, there is no way to know your reverse tunnel address, which is necessary when adding a trusted cluster.
This PR adds a new field under cluster information `Public SSH Tunnel`.

Note that this field is not currently exposed, here's the PR on cloud to add it: gravitational/teleport#10133

Screenshot: 
Screenshot from 2022-02-03 16-34-15
(new field `Public SSH Tunnel` at the bottom of **Cluster Information**)

Closes gravitational/cloud#950

### CODE REVIEW

**Review by kimlisa — COMMENTED** [review]
hi matheus! couple of things:

1) could you update our storybook and ensure it is working as you intend it, you can run story book by running command in root `yarn storybook`. I always run `yarn test` and `yarn tsc` before committing (don't worry it's faster than teleport tests) to get instant feedback. You'll note that some snapshot will break from your changes. Make sure the breaking changes is what you expect and then update the snapshot by running `yarn test -u <name of test file>`

2) with UI related changes being so visual, it is super helpful if we add screenshots to our PRs

**Comment by mcbattirola** [comment]
Hi @kimlisa ! Thanks for the explanations!

I added a new entry to storybook and a screenshot

**Review by kimlisa — APPROVED** [review]
lgtm, but can we merge after the backend changes are merged?

**Comment by mcbattirola** [comment]
https://github.com/gravitational/teleport/pull/10133 is merged, I'll merge this one now

**Pull request merged**
