### PR TITLE
Fix typo in makeCluster

### PR DESCRIPTION
**Pull request by rudream**
## Purpose

Fixes a typo that was causing a console error and invalid `connectedText`

### CODE REVIEW

**Review by hatched — APPROVED** [review]
Thanks

**Review by kimlisa — CHANGES_REQUESTED** [review]
lets add a test for this file, we normally do testing but this is probably an old one

**Comment by rudream** [comment]
@kimlisa We don't do any testing for `makeXXX` files, the only way a test here would help is if we mocked the raw back-end response, which we don't do in any of our tests afaik.

**Review by kimlisa — APPROVED** [review]
just one item in mocked array is fine

**Pull request merged**
