### PR TITLE
Update FormLogin.tsx

### PR DESCRIPTION
**Pull request by t-rutter**
Changed login form 'Authenticator code' input field type from 'text' to 'tel'.
In html the two are functional the same, But allows for client improvements for number input.

Allows 'Authenticator code' autofill on iOS 15 and Safari 15 .
On other devices an the onscreen keyboard may change to an number pad for easier code input.

### CODE REVIEW

**Comment by t-rutter** [comment]
Cloud someone please test this .😄 thanks
Referenced from https://github.com/gravitational/teleport/discussions/10389

**Review by zmb3 — APPROVED** [review]

**Comment by kimlisa** [comment]
Thanks for the PR! We need to update typing and fix a snapshot before this can be merged. If you'd like to do this, the instructions are below, otherwise we are happy to take over:

Step 1: in [FieldInput](https://github.com/gravitational/webapps/blob/master/packages/shared/components/FieldInput/FieldInput.tsx#L63) component, add a type `'tel'`
Step 2: update snapshot `yarn test -u FormLogin.test`

**Comment by t-rutter** [comment]
Ok, I think I figured it out.
I've ran
> brew install yarn

Then in the repo folder
> yarn install
> yarn test -u FormLogin.test
and then
> yarn run test

But got an errors in 'packages/teleport/src/components/FormLogin/FormLogin.story.test.tsx'.
So also ran
> yarn test -u FormLogin.story.test
then
> yarn run test
:D no errors reported 

Even managed to work out the dev proxy test
> yarn start-teleport --target=https://teleport.mydomain.com:443/web
It looks like it works, autofills in safari or numberpad is displayed when entering the code

**Comment by kimlisa** [comment]
awesome, just one more change needed to get the tests passing, in [FieldInput](https://github.com/gravitational/webapps/blob/master/packages/shared/components/FieldInput/FieldInput.tsx#L63) file, add a type 'tel': `| 'tel'`

**Review by kimlisa — APPROVED** [review]

**Comment by zmb3** [comment]
Thanks for the contribution, @t-rutter 🙌

**Pull request merged**
